///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace MyAssays.Wizard.RanorexTests
{
    public partial class AddUserToXML
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void AddUser(string username, string group)
        {
        	var usersXMLPath = Path.Combine(Environment.ExpandEnvironmentVariables("%PROGRAMDATA%"), "MyAssays", "MyAssays Desktop ES", "Manager", "Users.xml");
        	var usersXMLText = File.ReadAllText(usersXMLPath).Replace("</Users>", String.Empty);
        	
        	var userXMLText = String.Format("<User UserName=\"{0}\" FullName=\"{1}\" Group=\"{2}\" Enabled=\"true\" Locked=\"false\" Level=\"User\" LastPasswordChange=\"2017-11-08T12:47:24.1679674Z\">" +
 						     " <PasswordHistory />" +
					         " </User>" +
					         " </Users>", username, username, group);
        	
        	File.WriteAllText(usersXMLPath, usersXMLText + userXMLText);
        }

    }
}