///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using System.IO;

namespace MyAssays.Wizard.RanorexTests
{
    public partial class AddUserToUsersXML
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void AddUser(string group, string username)
        {
        	var usersXMLPath = Path.Combine(Environment.ExpandEnvironmentVariables("%PROGRAMDATA%"), "MyAssays", "MyAssays Desktop ES", "Manager", "Users.xml");
        	var usersXMLText = File.ReadAllText(madConfigPath);
        	
        	var userAppendXML = String.Format("  <User UserName=\"testuser1\" FullName=\"{0}\" Enabled=\"true\" Locked=\"false\" Group=\"{1}\" Level=\"User\" LastPasswordChange=\"2017-11-08T12:18:42.0649262Z\">\n" +
							  "    <PasswordHistory />\n" +
							  "  </User>\n" +
							  "</Users>", 
							  username, group);
        	
        	usersXMLText.Replace("</Users>", String.Empty);
        	
        	File.WriteAllText(usersXMLPath, usersXMLText + userAppendXML);
        }

    }
}