///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AnalysisEditXXXOperationsProtocol recording.
    /// </summary>
    [TestModule("86bc02f0-96d3-4f0b-b278-9a2cc7fb1f85", ModuleType.Recording, 1)]
    public partial class AnalysisEditXXXOperationsProtocol : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static AnalysisEditXXXOperationsProtocol instance = new AnalysisEditXXXOperationsProtocol();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AnalysisEditXXXOperationsProtocol()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AnalysisEditXXXOperationsProtocol Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.MeasurementsTab' at Center.", repo.ProtocolAnalysisDesktop.MeasurementsTabInfo, new RecordItemIndex(0));
            repo.ProtocolAnalysisDesktop.MeasurementsTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            ValidatePadIsReadOnly();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.TabControlGrid1.Plate_Tab' at Center.", repo.ProtocolAnalysisDesktop.TabControlGrid1.Plate_TabInfo, new RecordItemIndex(3));
            repo.ProtocolAnalysisDesktop.TabControlGrid1.Plate_Tab.Click();
            Delay.Milliseconds(200);
            
            ValidatePlateIsReadOnly();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.TabControlGrid1.ChartTab' at Center.", repo.ProtocolAnalysisDesktop.TabControlGrid1.ChartTabInfo, new RecordItemIndex(5));
            repo.ProtocolAnalysisDesktop.TabControlGrid1.ChartTab.Click();
            Delay.Milliseconds(200);
            
            ToggleFlagPointOnMeasurementsChart("1", "0.374");
            Delay.Milliseconds(0);
            
            ValidatePointFlagState(ValueConverter.ArgumentFromString<bool>("expectedState", "False"), "1", "0.374");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.TabControlGrid1.ContainerIDsTab' at 64;13.", repo.ProtocolAnalysisDesktop.TabControlGrid1.ContainerIDsTabInfo, new RecordItemIndex(8));
            repo.ProtocolAnalysisDesktop.TabControlGrid1.ContainerIDsTab.Click("64;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.TabControlGrid1.SeriesDataGrid' at 12;16.", repo.ProtocolAnalysisDesktop.TabControlGrid1.SeriesDataGridInfo, new RecordItemIndex(9));
            repo.ProtocolAnalysisDesktop.TabControlGrid1.SeriesDataGrid.Click("12;16");
            Delay.Milliseconds(200);
            
            ValidatePlateIDsIsReadonly();
            Delay.Milliseconds(0);
            
            ClickCanvasCell(ValueConverter.ArgumentFromString<int>("index", "0"));
            Delay.Milliseconds(0);
            
            CheckNotFlagged(ValueConverter.ArgumentFromString<int>("index", "0"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.CalculateButton'.", repo.ProtocolAnalysisDesktop.CalculateButtonInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.CalculateButtonInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.Purge'.", repo.ProtocolAnalysisDesktop.PurgeInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.PurgeInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.RollBack'.", repo.ProtocolAnalysisDesktop.RollBackInfo, new RecordItemIndex(15));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.RollBackInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            OpenPropertiesEditor();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.ButtonAdd'.", repo.ProtocolAnalysisDesktop.ButtonAddInfo, new RecordItemIndex(17));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ButtonAddInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.ButtonRemove'.", repo.ProtocolAnalysisDesktop.ButtonRemoveInfo, new RecordItemIndex(18));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ButtonRemoveInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.inputMatrixFirstRow'.", repo.ProtocolAnalysisDesktop.inputMatrixFirstRowInfo, new RecordItemIndex(19));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.inputMatrixFirstRowInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsReadOnly='True') on item 'ProtocolAnalysisDesktop.OutputMatrixFirstRow'.", repo.ProtocolAnalysisDesktop.OutputMatrixFirstRowInfo, new RecordItemIndex(20));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.OutputMatrixFirstRowInfo, "IsReadOnly", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Evaluation' at Center.", repo.ProtocolAnalysisDesktop.EvaluationInfo, new RecordItemIndex(21));
            repo.ProtocolAnalysisDesktop.Evaluation.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.AddEvalutionTable'.", repo.ProtocolAnalysisDesktop.AddEvalutionTableInfo, new RecordItemIndex(22));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.AddEvalutionTableInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.RemoveEvalutionTable'.", repo.ProtocolAnalysisDesktop.RemoveEvalutionTableInfo, new RecordItemIndex(23));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.RemoveEvalutionTableInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.EvaluationsTable1' at 58;4.", repo.ProtocolAnalysisDesktop.EvaluationsTable1Info, new RecordItemIndex(24));
            repo.ProtocolAnalysisDesktop.EvaluationsTable1.Click("58;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsReadOnly='True') on item 'ProtocolAnalysisDesktop.EvaluationExpressionInput'.", repo.ProtocolAnalysisDesktop.EvaluationExpressionInputInfo, new RecordItemIndex(25));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.EvaluationExpressionInputInfo, "IsReadOnly", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.AddEvalution'.", repo.ProtocolAnalysisDesktop.AddEvalutionInfo, new RecordItemIndex(26));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.AddEvalutionInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.RemoveEvalution'.", repo.ProtocolAnalysisDesktop.RemoveEvalutionInfo, new RecordItemIndex(27));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.RemoveEvalutionInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsReadOnly='True') on item 'ProtocolAnalysisDesktop.EvaluationDescription'.", repo.ProtocolAnalysisDesktop.EvaluationDescriptionInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.EvaluationDescriptionInfo, "IsReadOnly", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.EvaluationMatrixDropdown'.", repo.ProtocolAnalysisDesktop.EvaluationMatrixDropdownInfo, new RecordItemIndex(29));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.EvaluationMatrixDropdownInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.EvaluationUpButton'.", repo.ProtocolAnalysisDesktop.EvaluationUpButtonInfo, new RecordItemIndex(30));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.EvaluationUpButtonInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.EvaluationDownButton'.", repo.ProtocolAnalysisDesktop.EvaluationDownButtonInfo, new RecordItemIndex(31));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.EvaluationDownButtonInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Validation' at Center.", repo.ProtocolAnalysisDesktop.ValidationInfo, new RecordItemIndex(32));
            repo.ProtocolAnalysisDesktop.Validation.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.AddValidationTable'.", repo.ProtocolAnalysisDesktop.AddValidationTableInfo, new RecordItemIndex(33));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.AddValidationTableInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.RemoveValidationTable'.", repo.ProtocolAnalysisDesktop.RemoveValidationTableInfo, new RecordItemIndex(34));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.RemoveValidationTableInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.ValidationsTable1' at 74;10.", repo.ProtocolAnalysisDesktop.ValidationsTable1Info, new RecordItemIndex(35));
            repo.ProtocolAnalysisDesktop.ValidationsTable1.Click("74;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.ValidationExpression'.", repo.ProtocolAnalysisDesktop.ValidationExpressionInfo, new RecordItemIndex(36));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ValidationExpressionInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.AddValidation1'.", repo.ProtocolAnalysisDesktop.AddValidation1Info, new RecordItemIndex(37));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.AddValidation1Info, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.RemoveValidation1'.", repo.ProtocolAnalysisDesktop.RemoveValidation1Info, new RecordItemIndex(38));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.RemoveValidation1Info, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.ValidationMoveUp'.", repo.ProtocolAnalysisDesktop.ValidationMoveUpInfo, new RecordItemIndex(39));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ValidationMoveUpInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.ValidationMoveDown'.", repo.ProtocolAnalysisDesktop.ValidationMoveDownInfo, new RecordItemIndex(40));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ValidationMoveDownInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsReadOnly='True') on item 'ProtocolAnalysisDesktop.ValidationDescription'.", repo.ProtocolAnalysisDesktop.ValidationDescriptionInfo, new RecordItemIndex(41));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ValidationDescriptionInfo, "IsReadOnly", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.ValidationMatrixDropdown'.", repo.ProtocolAnalysisDesktop.ValidationMatrixDropdownInfo, new RecordItemIndex(42));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ValidationMatrixDropdownInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.TabPageXML' at Center.", repo.ProtocolAnalysisDesktop.TabPageXMLInfo, new RecordItemIndex(43));
            repo.ProtocolAnalysisDesktop.TabPageXML.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.xmlText'.", repo.ProtocolAnalysisDesktop.xmlTextInfo, new RecordItemIndex(44));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.xmlTextInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Report' at Center.", repo.ProtocolAnalysisDesktop.ReportInfo, new RecordItemIndex(45));
            repo.ProtocolAnalysisDesktop.Report.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.ReportMoveDown'.", repo.ProtocolAnalysisDesktop.ReportMoveDownInfo, new RecordItemIndex(46));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ReportMoveDownInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.ReportMoveUp'.", repo.ProtocolAnalysisDesktop.ReportMoveUpInfo, new RecordItemIndex(47));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ReportMoveUpInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            ValidateAddElementNotVisible();
            Delay.Milliseconds(0);
            
            ValidateRemoveElementNotVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.SampleTable1' at 54;6.", repo.ProtocolAnalysisDesktop.SampleTable1Info, new RecordItemIndex(50));
            repo.ProtocolAnalysisDesktop.SampleTable1.Click("54;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsReadOnly='True') on item 'ProtocolAnalysisDesktop.SampleTableId'.", repo.ProtocolAnalysisDesktop.SampleTableIdInfo, new RecordItemIndex(51));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SampleTableIdInfo, "IsReadOnly", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.ReportIncludeCheckbox'.", repo.ProtocolAnalysisDesktop.ReportIncludeCheckboxInfo, new RecordItemIndex(52));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ReportIncludeCheckboxInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsReadOnly='True') on item 'ProtocolAnalysisDesktop.TitleInput'.", repo.ProtocolAnalysisDesktop.TitleInputInfo, new RecordItemIndex(53));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.TitleInputInfo, "IsReadOnly", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.SampleTableIncludePositions'.", repo.ProtocolAnalysisDesktop.SampleTableIncludePositionsInfo, new RecordItemIndex(54));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SampleTableIncludePositionsInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Matrices' at Center.", repo.ProtocolAnalysisDesktop.MatricesInfo, new RecordItemIndex(55));
            repo.ProtocolAnalysisDesktop.Matrices.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.MyRawData' at Center.", repo.ProtocolAnalysisDesktop.MyRawDataInfo, new RecordItemIndex(56));
            repo.ProtocolAnalysisDesktop.MyRawData.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsReadOnly='True') on item 'ProtocolAnalysisDesktop.Calc2Property'.", repo.ProtocolAnalysisDesktop.Calc2PropertyInfo, new RecordItemIndex(57));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.Calc2PropertyInfo, "IsReadOnly", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.Precision'.", repo.ProtocolAnalysisDesktop.PrecisionInfo, new RecordItemIndex(58));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.PrecisionInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.SignificantFiguresDropdown'.", repo.ProtocolAnalysisDesktop.SignificantFiguresDropdownInfo, new RecordItemIndex(59));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SignificantFiguresDropdownInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.IncludeInMatrixTableCheckbox'.", repo.ProtocolAnalysisDesktop.IncludeInMatrixTableCheckboxInfo, new RecordItemIndex(60));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.IncludeInMatrixTableCheckboxInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.IncludeInSamplesTableCheckbox'.", repo.ProtocolAnalysisDesktop.IncludeInSamplesTableCheckboxInfo, new RecordItemIndex(61));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.IncludeInSamplesTableCheckboxInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.SampleTableReplicatesDropdown'.", repo.ProtocolAnalysisDesktop.SampleTableReplicatesDropdownInfo, new RecordItemIndex(62));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SampleTableReplicatesDropdownInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Notes' at Center.", repo.ProtocolAnalysisDesktop.NotesInfo, new RecordItemIndex(63));
            repo.ProtocolAnalysisDesktop.Notes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (IsManipulationEnabled='False') on item 'ProtocolAnalysisDesktop.NotesTextarea'.", repo.ProtocolAnalysisDesktop.NotesTextareaInfo, new RecordItemIndex(64));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.NotesTextareaInfo, "IsManipulationEnabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Ribbon' at 13;37.", repo.ProtocolAnalysisDesktop.RibbonInfo, new RecordItemIndex(65));
            repo.ProtocolAnalysisDesktop.Ribbon.Click("13;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.SaveTab'.", repo.ProtocolAnalysisDesktop.SaveTabInfo, new RecordItemIndex(66));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SaveTabInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.SaveProtocolButton'.", repo.ProtocolAnalysisDesktop.SaveProtocolButtonInfo, new RecordItemIndex(67));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SaveProtocolButtonInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.SaveProtocolAsButton'.", repo.ProtocolAnalysisDesktop.SaveProtocolAsButtonInfo, new RecordItemIndex(68));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SaveProtocolAsButtonInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.SaveResultAsButton'.", repo.ProtocolAnalysisDesktop.SaveResultAsButtonInfo, new RecordItemIndex(69));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.SaveResultAsButtonInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ProtocolAnalysisDesktop.ResultNamingButton'.", repo.ProtocolAnalysisDesktop.ResultNamingButtonInfo, new RecordItemIndex(70));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.ResultNamingButtonInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
