///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AnalysisEditXXXOperationsResult recording.
    /// </summary>
    [TestModule("99f029aa-72cb-4170-b582-4d712497a7d3", ModuleType.Recording, 1)]
    public partial class AnalysisEditXXXOperationsResult : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static AnalysisEditXXXOperationsResult instance = new AnalysisEditXXXOperationsResult();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AnalysisEditXXXOperationsResult()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AnalysisEditXXXOperationsResult Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.ReportRibbonTab' at Center.", repo.ResultsAnalysis.ReportRibbonTab.SelfInfo, new RecordItemIndex(0));
            repo.ResultsAnalysis.ReportRibbonTab.Self.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.PageView' at 35;37.", repo.ResultsAnalysis.PageViewInfo, new RecordItemIndex(1));
            repo.ResultsAnalysis.PageView.Click("35;37");
            Delay.Milliseconds(200);
            
            ValidateTemplateButtonsNotVisisble();
            Delay.Milliseconds(0);
            
            ValidateInsertHeaderFooterNotVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.ResultsTab' at Center.", repo.ResultsAnalysis.ResultsTabInfo, new RecordItemIndex(4));
            repo.ResultsAnalysis.ResultsTab.Click();
            Delay.Milliseconds(200);
            
            FlagPoint("1", "0.393");
            Delay.Milliseconds(0);
            
            ValidatePointFlagState(ValueConverter.ArgumentFromString<bool>("expectedState", "False"), "1", "0.393");
            Delay.Milliseconds(0);
            
            ValidateFlagsPanelCheckboxNotExist();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.SomeList' at 44;35.", repo.ResultsAnalysis.SomeListInfo, new RecordItemIndex(8));
            repo.ResultsAnalysis.SomeList.Click("44;35");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ResultsAnalysis.SaveTab'.", repo.ResultsAnalysis.SaveTabInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.ResultsAnalysis.SaveTabInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ResultsAnalysis.SaveButton'.", repo.ResultsAnalysis.SaveButtonInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.ResultsAnalysis.SaveButtonInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ResultsAnalysis.SaveResultsAs'.", repo.ResultsAnalysis.SaveResultsAsInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.ResultsAnalysis.SaveResultsAsInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'ResultsAnalysis.SaveProtocolAs'.", repo.ResultsAnalysis.SaveProtocolAsInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.ResultsAnalysis.SaveProtocolAsInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
