///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BestFitFit_MethodsPropertyEditor recording.
    /// </summary>
    [TestModule("42e9b33a-0dd0-45b9-a9f4-573c1981fbec", ModuleType.Recording, 1)]
    public partial class BestFitFit_MethodsPropertyEditor : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static BestFitFit_MethodsPropertyEditor instance = new BestFitFit_MethodsPropertyEditor();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BestFitFit_MethodsPropertyEditor()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BestFitFit_MethodsPropertyEditor Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            OpenPropertiesEditor();
            Delay.Milliseconds(0);
            
            selectTransform(ValueConverter.ArgumentFromString<int>("index", "0"));
            Delay.Milliseconds(0);
            
            Set_Value_FitMethod_cb("3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.FitMethods' at Center.", repo.ResultsAnalysis.FitMethodsInfo, new RecordItemIndex(3));
            repo.ResultsAnalysis.FitMethods.Click();
            Delay.Milliseconds(200);
            
            UncheckAllItems(repo.ResultsAnalysis.ListFits);
            Delay.Milliseconds(0);
            
            CheckDisableToCheckAtLeastLastCheckbox(repo.ResultsAnalysis.ListFits);
            Delay.Milliseconds(0);
            
            UncheckAllItems(repo.ResultsAnalysis.ListWeighting);
            Delay.Milliseconds(0);
            
            CheckDisableToCheckAtLeastLastCheckbox(repo.ResultsAnalysis.ListWeighting);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.FitMethods' at Center.", repo.ResultsAnalysis.FitMethodsInfo, new RecordItemIndex(8));
            repo.ResultsAnalysis.FitMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.XML' at Center.", repo.ResultsAnalysis.XMLInfo, new RecordItemIndex(9));
            repo.ResultsAnalysis.XML.Click();
            Delay.Milliseconds(200);
            
            CheckXML_Text("BestFitMethod_LinerY2.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.Transforms' at Center.", repo.ResultsAnalysis.TransformsInfo, new RecordItemIndex(11));
            repo.ResultsAnalysis.Transforms.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.FitMethods' at Center.", repo.ResultsAnalysis.FitMethodsInfo, new RecordItemIndex(12));
            repo.ResultsAnalysis.FitMethods.Click();
            Delay.Milliseconds(200);
            
            CheckAllItems(repo.ResultsAnalysis.ListFits);
            Delay.Milliseconds(0);
            
            CheckAllItems(repo.ResultsAnalysis.ListWeighting);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.FitMethods' at Center.", repo.ResultsAnalysis.FitMethodsInfo, new RecordItemIndex(15));
            repo.ResultsAnalysis.FitMethods.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.XML' at Center.", repo.ResultsAnalysis.XMLInfo, new RecordItemIndex(16));
            repo.ResultsAnalysis.XML.Click();
            Delay.Milliseconds(200);
            
            CheckXML_Text("BestFitMethod_AllAll.txt");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
