///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;
using System.Reflection;
using System.Xml;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace MyAssays.Wizard.RanorexTests
{
    public partial class BlankConcentrationsMultiplexProtocols
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void changeXML(string xml)
        {
        	string pathNewXML = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), String.Format(@"Inputs\MatrixTransform\{0}", xml));
        	Report.Log(ReportLevel.Info, "Clipboard", "Set file content to clipboard.");
            System.Windows.Forms.Clipboard.SetText(File.ReadAllText(pathNewXML));
        	
        	repo.ProtocolAnalysisDesktop.xmlElement.Click();
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'TemplateDocx'.");
            Keyboard.Press("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Seconds(1);
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Vkey}{LControlKey up}' with focus on 'TemplateDocx'.");
            Keyboard.Press("{LControlKey down}{Vkey}{LControlKey up}");
            Delay.Seconds(1);
        }

        public void checkNumericFormatType(string expectedValue)
        {
        	var xmlText = repo.ProtocolAnalysisDesktop.xmlText.Element.GetAttributeValueText("XmlText");
        	
        	if(xmlText.Contains(expectedValue))
        	{
        		Report.Success("Property 'NumericalFormatting' was changed.");
        	}
        	else
        	{
        		Report.Success("Property 'NumericalFormatting' was not changed.");
        	}
        }

        public void toWidescreen(int toLeft)
        {
        	if(repo.ProtocolAnalysisDesktop.PropertyEditorPanel.Element.ScreenRectangle.Width < (repo.ProtocolAnalysisDesktop.Self.ScreenRectangle.Width / 3))
        	{
//       start coordinates 	
        	var x = repo.ProtocolAnalysisDesktop.PropertyEditorPanel.Element.ScreenLocation.X - 5;
			var y = repo.ProtocolAnalysisDesktop.PropertyEditorPanel.Element.ScreenLocation.Y + 30;
			
			Mouse.MoveTo(new Point(x, y));          			
        	Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        	Delay.Seconds(1);
        	Mouse.MoveTo(new Point(x - toLeft, y), 2000);
        	Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        	Delay.Seconds(1);
        	}
        }

        public void openProperties(Ranorex.Adapter adapter)
        {
        	if (!adapter.Visible)
        	{
        		repo.ProtocolAnalysisDesktop.Properties.Click();
        	}
        	else
        	{
        		Report.Screenshot();
        	}
        }

        public void RunAnalysis(string protocolName)
        {
        	StartAnalysisHelper.Protocol = protocolName;
            StartAnalysisHelper.StartAnalysis();
            Delay.Seconds(HelperConstants.TIME_TO_OPEN_PROTOCOL);
        }

        public void CheckReportXMLByPattern(string fileName)
        {
        	var filePath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "TransformsTests", "ReportPatterns", fileName);

        	string reportPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), @"temp\1");
        	string[] reports = Directory.GetFiles(reportPath, "*.report.xml");
        	
        	var expected = File.ReadAllText(filePath).Replace("\n", String.Empty).Replace("\r", String.Empty);
        	var actual = File.ReadAllText(reports[0]).Replace(",", ".").Replace("\n", String.Empty).Replace("\r", String.Empty);
        	        	
        	Validate.IsTrue(actual.Contains(expected), "Validate report xml file");
        }

        public void CheckGoodnessMeasure()
        {
        	string reportPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), @"temp\1");
        	string[] reports = Directory.GetFiles(reportPath, "*.analysiscontrol.xml");
        	
        	 XmlDocument doc = new XmlDocument();
        	 doc.LoadXml(File.ReadAllText(reports[0]));
		
		     XmlElement root = doc.DocumentElement;
		     
		     //first tab 
		     var node = root.SelectSingleNode("//GroupTable[@Id='DescriptionTransformContent5GoodnessTable1']/Row[1]/Col[2]");
		     Validate.AreEqual(node.InnerText, "1", "Check R²");
        }

        public void CheckReportConcentrations()
        {
        	string reportPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), @"temp\1");
        	string[] reports = Directory.GetFiles(reportPath, "*.analysiscontrol.xml");
        	
        	 XmlDocument doc = new XmlDocument();
        	 doc.LoadXml(File.ReadAllText(reports[0]));
		
		     XmlElement root = doc.DocumentElement;
		     
		     //first tab
		     var node = root.SelectSingleNode("//GroupTable[@Id='DescriptionTransformContent4CoefficientTable1']/Row[1]/Col[2]");
		     Validate.AreEqual(node.InnerText, "0.274479", "Check a");  
 
		     node = root.SelectSingleNode("//GroupTable[@Id='DescriptionTransformContent4CoefficientTable1']/Row[2]/Col[2]");
		     Validate.AreEqual(node.InnerText, "5.07713", "Check b");
		     
		     node = root.SelectSingleNode("//GroupTable[@Id='DescriptionTransformContent4CoefficientTable1']/Row[3]/Col[2]");
		     Validate.AreEqual(node.InnerText, "0.192931", "Check c");
		     
		     node = root.SelectSingleNode("//GroupTable[@Id='DescriptionTransformContent4CoefficientTable1']/Row[4]/Col[2]");
		     Validate.AreEqual(node.InnerText, "0.0000319111", "Check d");
        }

        public void ExtractProtocol(string resultFileName)
        {
        	var reportPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "MyAssays\\Results\\");
        	ExtractProtocolHelper.DeleteTempFolder();
        	ExtractProtocolHelper.ExtractResultsTo(null, null, Directory.GetFiles(reportPath, "*.assay-results")[0]);
        }

        public void ValidateStandardCurveFitTabExists()
        {
        	Validate.IsTrue(repo.ResultsAnalysis.StandardCurveFitTabInfo.Exists() && repo.ResultsAnalysis.StandardCurveFitTab.Visible, 
        	                "Validate Standard Curve Fit tab exists");
        }

        public void ValidateSAAMsDoNotExist()
        {
        	Validate.AreEqual(repo.ResultsAnalysis.SaamsListBox1.Self.Find<Ranorex.WpfElement>(".//listitem").Count,0, "Validate SAAMs did not appear");
        }

        public void WaitForCalculation()
        {
        	HelperConstants.waitForCalculation();
        }

        public void CheckConcentrations()
        {
        	var cells = (Dictionary<int, List<Tuple<string, bool, Color>>>)repo.MyAssaysDesktopAnalysis.MultiplexConcentrationsEditor.Element.GetAttributeValue("ConcentrationCells");
        	
        	var cellsValues = ParamTableHelper.GetCellsStringValue(cells);

        	var startValue = 0.125;
        	
        	foreach(var currentValue in cellsValues)
        	{
        		var expectedValue = startValue.ToString();
        		if(decimalSeparator.Equals(","))
        			expectedValue = expectedValue.Replace(".", ",");
        		else
        			expectedValue = expectedValue.Replace(",", ".");

        		Validate.AreEqual(currentValue, expectedValue, String.Format("Validate concentration value is {0}. Actual: {1}", expectedValue,  currentValue));
        		startValue = startValue * 2;
        	}
        }

        public void CheckConcentrationsInDescription()
        {
        	var expectedText = "(0,125;0,25;0,5;1)";
        	if(decimalSeparator.Equals("."))
        		expectedText = expectedText.Replace(",", ".").Replace(";", ",");
        	Validate.IsTrue(repo.ProtocolAnalysisDesktop.TransformIndex1Description.TextValue.Contains(expectedText), String.Format("Validate description contains text {0}", expectedText));
        }

        public void selectTransform(int num)
        {
        	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.TransformList item' at Center.");
            repo.ProtocolAnalysisDesktop.Transforms1.Children[num].Click();
            Delay.Seconds(1);
        }

        public void DeleteResults()
        {
        	CleanDataHelper.DeleteResults();
        }

        public void CheckStartValues()
        {
        	var cells = (Dictionary<int, List<Tuple<string, bool, Color>>>)repo.MyAssaysDesktopAnalysis.MultiplexConcentrationsEditor.Element.GetAttributeValue("PlexCells");
       
        	var cellsValues = ParamTableHelper.GetCellsStringValue(cells);
        	
        	Validate.AreEqual(cellsValues[0], String.Format("0{0}125", decimalSeparator), String.Format("Validate first start value is 0{0}125", decimalSeparator));
        	Validate.AreEqual(cellsValues[1], String.Format("0{0}125", decimalSeparator), String.Format("Validate second start value is 0{0}125", decimalSeparator));
        }

        public void ValidateAnalyte2TabExists()
        {
        	Validate.IsTrue(repo.ResultsAnalysis.Analyte2ChartTabInfo.Exists() && repo.ResultsAnalysis.Analyte2ChartTab.Visible, 
        	                "Validate Standard Curve Fit tab exists");
        }

        public void ValidateAnalyte1TabExists()
        {
        	Validate.IsTrue(repo.ResultsAnalysis.Analyte1ChartTabInfo.Exists() && repo.ResultsAnalysis.Analyte1ChartTab.Visible, 
        	                "Validate Standard Curve Fit tab exists");
        }

    }
}