///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BlankConcentrationsMultiplexProtocols recording.
    /// </summary>
    [TestModule("8cfa6deb-baf3-4c41-a8bf-bcd2c4ff2787", ModuleType.Recording, 1)]
    public partial class BlankConcentrationsMultiplexProtocols : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static BlankConcentrationsMultiplexProtocols instance = new BlankConcentrationsMultiplexProtocols();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BlankConcentrationsMultiplexProtocols()
        {
            decimalSeparator = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BlankConcentrationsMultiplexProtocols Instance
        {
            get { return instance; }
        }

#region Variables

        string _decimalSeparator;

        /// <summary>
        /// Gets or sets the value of variable decimalSeparator.
        /// </summary>
        [TestVariable("6aed7c2c-b7a3-4bbb-b30b-fd0eade5bb4f")]
        public string decimalSeparator
        {
            get { return _decimalSeparator; }
            set { _decimalSeparator = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            DeleteResults();
            Delay.Milliseconds(0);
            
            RunAnalysis("MultiplexProtocol12x8With4BlankSamples.assay-protocol");
            Delay.Milliseconds(0);
            
            openProperties(repo.ProtocolAnalysisDesktop.Transforms);
            Delay.Milliseconds(0);
            
            toWidescreen(ValueConverter.ArgumentFromString<int>("toLeft", "400"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.ButtonAdd' at 29;11.", repo.ProtocolAnalysisDesktop.ButtonAddInfo, new RecordItemIndex(4));
            repo.ProtocolAnalysisDesktop.ButtonAdd.Click("29;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
            selectTransform(ValueConverter.ArgumentFromString<int>("num", "14"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.CreateTransform' at 26;6.", repo.ProtocolAnalysisDesktop.CreateTransformInfo, new RecordItemIndex(7));
            repo.ProtocolAnalysisDesktop.CreateTransform.Click("26;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(8));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.StandardTypeDropdown' at Center.", repo.ProtocolAnalysisDesktop.StandardTypeDropdownInfo, new RecordItemIndex(9));
            repo.ProtocolAnalysisDesktop.StandardTypeDropdown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(10));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopAnalysis.Blank' at 37;5.", repo.MyAssaysDesktopAnalysis.BlankInfo, new RecordItemIndex(11));
            repo.MyAssaysDesktopAnalysis.Blank.Click("37;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.ConcentrationsDropdown' at 55;9.", repo.ProtocolAnalysisDesktop.ConcentrationsDropdownInfo, new RecordItemIndex(12));
            repo.ProtocolAnalysisDesktop.ConcentrationsDropdown.Click("55;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopAnalysis.Grid.FactorInput' at 42;10.", repo.MyAssaysDesktopAnalysis.Grid.FactorInputInfo, new RecordItemIndex(13));
            repo.MyAssaysDesktopAnalysis.Grid.FactorInput.Click("42;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(14));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2'.", new RecordItemIndex(15));
            Keyboard.Press("2");
            Delay.Milliseconds(0);
            
            CheckConcentrations();
            Delay.Milliseconds(0);
            
            CheckStartValues();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopAnalysis.SomeContainer.Analyte2' at 30;6.", repo.MyAssaysDesktopAnalysis.SomeContainer.Analyte2Info, new RecordItemIndex(18));
            repo.MyAssaysDesktopAnalysis.SomeContainer.Analyte2.Click("30;6");
            Delay.Milliseconds(200);
            
            CheckConcentrations();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.ConcentrationsDropdown' at 55;9.", repo.ProtocolAnalysisDesktop.ConcentrationsDropdownInfo, new RecordItemIndex(20));
            repo.ProtocolAnalysisDesktop.ConcentrationsDropdown.Click("55;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.CalculateButton' at Center.", repo.ProtocolAnalysisDesktop.CalculateButtonInfo, new RecordItemIndex(21));
            repo.ProtocolAnalysisDesktop.CalculateButton.Click();
            Delay.Milliseconds(200);
            
            WaitForCalculation();
            Delay.Milliseconds(0);
            
            WaitForCalculation();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ResultsAnalysis'.", repo.ResultsAnalysis.SelfInfo, new RecordItemIndex(24));
            Validate.Exists(repo.ResultsAnalysis.SelfInfo);
            Delay.Milliseconds(0);
            
            ValidateSAAMsDoNotExist();
            Delay.Milliseconds(0);
            
            ValidateAnalyte1TabExists();
            Delay.Milliseconds(0);
            
            ValidateAnalyte2TabExists();
            Delay.Milliseconds(0);
            
            ExtractProtocol("MultiplexProtocol12x8With4BlankSamples (1).assay-results");
            Delay.Milliseconds(0);
            
            CheckReportConcentrations();
            Delay.Milliseconds(0);
            
            CheckGoodnessMeasure();
            Delay.Milliseconds(0);
            
            CheckReportXMLByPattern("SCFMultiplexBlankConcentrations.txt");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
