///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UninstallMyAssays recording.
    /// </summary>
    [TestModule("84f5871f-6fc2-4367-96af-621633f18a5c", ModuleType.Recording, 1)]
    public partial class UninstallMyAssays : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static UninstallMyAssays instance = new UninstallMyAssays();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UninstallMyAssays()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UninstallMyAssays Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            SaveLogFiles();
            Delay.Milliseconds(0);
            
            UninstallMyAssays_Run_Application();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(2));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyAssaysDesktopSetup'.", repo.MyAssaysDesktopSetup.SelfInfo, new RecordItemIndex(3));
            Validate.Exists(repo.MyAssaysDesktopSetup.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyAssaysDesktopSetup.ButtonNext'.", repo.MyAssaysDesktopSetup.ButtonNextInfo, new RecordItemIndex(4));
            Validate.Exists(repo.MyAssaysDesktopSetup.ButtonNextInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_ButtonNext();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyAssaysDesktopSetup.ButtonRemove'.", repo.MyAssaysDesktopSetup.ButtonRemoveInfo, new RecordItemIndex(6));
            Validate.Exists(repo.MyAssaysDesktopSetup.ButtonRemoveInfo);
            Delay.Milliseconds(0);
            
            CloseMyAssays();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopSetup.ButtonRemove' at 15;9.", repo.MyAssaysDesktopSetup.ButtonRemoveInfo, new RecordItemIndex(8));
            repo.MyAssaysDesktopSetup.ButtonRemove.Click("15;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Ready to remove MyAssays Desktop') on item 'MyAssaysDesktopSetup.UninstallMainText'.", repo.MyAssaysDesktopSetup.UninstallMainTextInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.MyAssaysDesktopSetup.UninstallMainTextInfo, "Text", "Ready to remove MyAssays Desktop");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyAssaysDesktopSetup.ButtonRemove'.", repo.MyAssaysDesktopSetup.ButtonRemoveInfo, new RecordItemIndex(10));
            Validate.Exists(repo.MyAssaysDesktopSetup.ButtonRemoveInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopSetup.ButtonRemove' at 74;15.", repo.MyAssaysDesktopSetup.ButtonRemoveInfo, new RecordItemIndex(11));
            repo.MyAssaysDesktopSetup.ButtonRemove.Click("74;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(12));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyAssaysDesktopSetup.ButtonFinish'.", repo.MyAssaysDesktopSetup.ButtonFinishInfo, new RecordItemIndex(13));
            Validate.Exists(repo.MyAssaysDesktopSetup.ButtonFinishInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopSetup.ButtonFinish' at 27;15.", repo.MyAssaysDesktopSetup.ButtonFinishInfo, new RecordItemIndex(14));
            repo.MyAssaysDesktopSetup.ButtonFinish.Click("27;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
