///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace MyAssays.Wizard.RanorexTests
{
    public partial class UninstallWorkout
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void LaunchWorkoutWizard()
        {
        	var installerRath = Path.Combine(StartAnalysisHelper.GetExecutingAssemblyPath(), "WorkOut", "WorkOut600.exe");
        	Report.Log(ReportLevel.Info, "Application", String.Format("Run application {0} with arguments '' in normal mode.", installerRath));
            Host.Local.RunApplication(installerRath, "", "", false);
        }

    }
}