///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateRackNotDisplaying recording.
    /// </summary>
    [TestModule("62f3ff37-b0c1-429f-b3db-96f3ceafaa73", ModuleType.Recording, 1)]
    public partial class ValidateRackNotDisplaying : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static ValidateRackNotDisplaying instance = new ValidateRackNotDisplaying();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateRackNotDisplaying()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateRackNotDisplaying Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.ProtocolWizard.IDontHaveAnyDataCheckbox' at 3;1.", repo.NewProtocolWizard.ProtocolWizard.IDontHaveAnyDataCheckboxInfo, new RecordItemIndex(0));
            repo.NewProtocolWizard.ProtocolWizard.IDontHaveAnyDataCheckbox.Click("3;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.ProtocolWizard.Next' at 29;17.", repo.NewProtocolWizard.ProtocolWizard.NextInfo, new RecordItemIndex(1));
            repo.NewProtocolWizard.ProtocolWizard.Next.Click("29;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewProtocolWizard.ProtocolWizard.Next' at 29;17.", repo.NewProtocolWizard.ProtocolWizard.NextInfo, new RecordItemIndex(2));
            repo.NewProtocolWizard.ProtocolWizard.Next.Click("29;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'NewProtocolWizard.ProtocolWizard.RackRadioButton'.", repo.NewProtocolWizard.ProtocolWizard.RackRadioButtonInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.NewProtocolWizard.ProtocolWizard.RackRadioButtonInfo, "Visible", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'NewProtocolWizard.ProtocolWizard.MyDataFormatList'.", repo.NewProtocolWizard.ProtocolWizard.MyDataFormatListInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.NewProtocolWizard.ProtocolWizard.MyDataFormatListInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
