///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WorkOutCommandLineDeactivation recording.
    /// </summary>
    [TestModule("ba50dc63-08a9-4350-8b41-b9e0416e4700", ModuleType.Recording, 1)]
    public partial class WorkOutCommandLineDeactivation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static WorkOutCommandLineDeactivation instance = new WorkOutCommandLineDeactivation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WorkOutCommandLineDeactivation()
        {
            serial = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WorkOutCommandLineDeactivation Instance
        {
            get { return instance; }
        }

#region Variables

        string _serial;

        /// <summary>
        /// Gets or sets the value of variable serial.
        /// </summary>
        [TestVariable("500cc70c-2b0c-4962-9b26-a420a7c00d9e")]
        public string serial
        {
            get { return _serial; }
            set { _serial = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Deactivate("4cbb81ae-05c7-4c79-8572-60303965c100", "$serial", "devteam@myassays.com");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
