///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The X_Axis_Spectral recording.
    /// </summary>
    [TestModule("cfc01806-cc00-4e71-9760-478e0a02547a", ModuleType.Recording, 1)]
    public partial class X_Axis_Spectral : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static X_Axis_Spectral instance = new X_Axis_Spectral();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public X_Axis_Spectral()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static X_Axis_Spectral Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            OpenPropertyEditor();
            Delay.Milliseconds(0);
            
            CheckTransformsParameters();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.CalculateButton' at Center.", repo.ProtocolAnalysisDesktop.CalculateButtonInfo, new RecordItemIndex(2));
            repo.ProtocolAnalysisDesktop.CalculateButton.Click();
            Delay.Milliseconds(200);
            
            waitForCalculation();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.HomeRibbonTab' at Center.", repo.ResultsAnalysis.HomeRibbonTabInfo, new RecordItemIndex(4));
            repo.ResultsAnalysis.HomeRibbonTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.PropertiesBttn' at Center.", repo.ResultsAnalysis.PropertiesBttnInfo, new RecordItemIndex(5));
            repo.ResultsAnalysis.PropertiesBttn.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.XY_Reduction_Spectral_nm' at Center.", repo.ResultsAnalysis.XY_Reduction_Spectral_nmInfo, new RecordItemIndex(6));
            repo.ResultsAnalysis.XY_Reduction_Spectral_nm.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(7));
            Delay.Duration(3000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Wavelength (nm)') on item 'ResultsAnalysis.X_AxisChartTitleWavelength'.", repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, new RecordItemIndex(8));
                Validate.Attribute(repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, "Text", "Wavelength (nm)", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.XY_Reduction_Spectral_um' at Center.", repo.ResultsAnalysis.XY_Reduction_Spectral_umInfo, new RecordItemIndex(9));
            repo.ResultsAnalysis.XY_Reduction_Spectral_um.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(10));
            Delay.Duration(3000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Wavelength (µm)') on item 'ResultsAnalysis.X_AxisChartTitleWavelength'.", repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, new RecordItemIndex(11));
                Validate.Attribute(repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, "Text", "Wavelength (µm)", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.XY_Reduction_Spectral_mm' at Center.", repo.ResultsAnalysis.XY_Reduction_Spectral_mmInfo, new RecordItemIndex(12));
            repo.ResultsAnalysis.XY_Reduction_Spectral_mm.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(13));
            Delay.Duration(3000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Wavelength (mm)') on item 'ResultsAnalysis.X_AxisChartTitleWavelength'.", repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, new RecordItemIndex(14));
                Validate.Attribute(repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, "Text", "Wavelength (mm)", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(14)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ResultsAnalysis.XY_Reduction_Spectral_cm' at Center.", repo.ResultsAnalysis.XY_Reduction_Spectral_cmInfo, new RecordItemIndex(15));
            repo.ResultsAnalysis.XY_Reduction_Spectral_cm.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(16));
            Delay.Duration(3000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Wavelength (cm)') on item 'ResultsAnalysis.X_AxisChartTitleWavelength'.", repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, new RecordItemIndex(17));
                Validate.Attribute(repo.ResultsAnalysis.X_AxisChartTitleWavelengthInfo, "Text", "Wavelength (cm)", Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
