///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyAssays.Wizard.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The XmlBondPropertyMTA recording.
    /// </summary>
    [TestModule("6259eb60-6703-42e9-b647-1befcc98cd33", ModuleType.Recording, 1)]
    public partial class XmlBondPropertyMTA : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyAssays_Wizard_RanorexTestsRepository repository.
        /// </summary>
        public static MyAssays_Wizard_RanorexTestsRepository repo = MyAssays_Wizard_RanorexTestsRepository.Instance;

        static XmlBondPropertyMTA instance = new XmlBondPropertyMTA();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public XmlBondPropertyMTA()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static XmlBondPropertyMTA Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            OpenPropertyEditor();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Transforms' at Center.", repo.ProtocolAnalysisDesktop.TransformsInfo, new RecordItemIndex(2));
            repo.ProtocolAnalysisDesktop.Transforms.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.ButtonAdd' at Center.", repo.ProtocolAnalysisDesktop.ButtonAddInfo, new RecordItemIndex(3));
            repo.ProtocolAnalysisDesktop.ButtonAdd.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(4));
            Delay.Duration(500, false);
            
            selectTransform(ValueConverter.ArgumentFromString<int>("num", "14"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.CreateTransform' at Center.", repo.ProtocolAnalysisDesktop.CreateTransformInfo, new RecordItemIndex(6));
            repo.ProtocolAnalysisDesktop.CreateTransform.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Matrices' at Center.", repo.ProtocolAnalysisDesktop.MatricesInfo, new RecordItemIndex(8));
            repo.ProtocolAnalysisDesktop.Matrices.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Total' at Center.", repo.ProtocolAnalysisDesktop.TotalInfo, new RecordItemIndex(9));
            repo.ProtocolAnalysisDesktop.Total.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2. Total') on item 'ProtocolAnalysisDesktop.Total'.", repo.ProtocolAnalysisDesktop.TotalInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.ProtocolAnalysisDesktop.TotalInfo, "Text", "2. Total");
            Delay.Milliseconds(0);
            
            inputText(repo.ProtocolAnalysisDesktop.NumericPresition, "7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.LabelingProperty' at Center.", repo.ProtocolAnalysisDesktop.LabelingPropertyInfo, new RecordItemIndex(12));
            repo.ProtocolAnalysisDesktop.LabelingProperty.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopAnalysis.AddButton' at Center.", repo.MyAssaysDesktopAnalysis.AddButtonInfo, new RecordItemIndex(13));
            repo.MyAssaysDesktopAnalysis.AddButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}'.", new RecordItemIndex(14));
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Label1'.", new RecordItemIndex(15));
            Keyboard.Press("Label1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopAnalysis.AddButton' at 46;12.", repo.MyAssaysDesktopAnalysis.AddButtonInfo, new RecordItemIndex(16));
            repo.MyAssaysDesktopAnalysis.AddButton.Click("46;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'x > 0'.", new RecordItemIndex(17));
            Keyboard.Press("x > 0");
            Delay.Milliseconds(0);
            
            checkLabelSummury("Label1, Label");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Checked to 'True' on item 'ProtocolAnalysisDesktop.DisplayValueBar'.", repo.ProtocolAnalysisDesktop.DisplayValueBarInfo, new RecordItemIndex(19));
            repo.ProtocolAnalysisDesktop.DisplayValueBar.Element.SetAttributeValue("Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.Report' at Center.", repo.ProtocolAnalysisDesktop.ReportInfo, new RecordItemIndex(20));
            repo.ProtocolAnalysisDesktop.Report.Click();
            Delay.Milliseconds(200);
            
            selectReportIem(ValueConverter.ArgumentFromString<int>("index", "1"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.ContentProperty' at Center.", repo.ProtocolAnalysisDesktop.ContentPropertyInfo, new RecordItemIndex(22));
            repo.ProtocolAnalysisDesktop.ContentProperty.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.FitEquationWithValues1' at Center.", repo.ProtocolAnalysisDesktop.FitEquationWithValues1Info, new RecordItemIndex(23));
            repo.ProtocolAnalysisDesktop.FitEquationWithValues1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopAnalysis.SomeContainer.ExcludeButton' at Center.", repo.MyAssaysDesktopAnalysis.SomeContainer.ExcludeButtonInfo, new RecordItemIndex(24));
            repo.MyAssaysDesktopAnalysis.SomeContainer.ExcludeButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.GoodnessMeasuresTable1' at Center.", repo.ProtocolAnalysisDesktop.GoodnessMeasuresTable1Info, new RecordItemIndex(25));
            repo.ProtocolAnalysisDesktop.GoodnessMeasuresTable1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyAssaysDesktopAnalysis.SomeContainer.ExcludeButton' at Center.", repo.MyAssaysDesktopAnalysis.SomeContainer.ExcludeButtonInfo, new RecordItemIndex(26));
            repo.MyAssaysDesktopAnalysis.SomeContainer.ExcludeButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProtocolAnalysisDesktop.TabPageXML' at Center.", repo.ProtocolAnalysisDesktop.TabPageXMLInfo, new RecordItemIndex(27));
            repo.ProtocolAnalysisDesktop.TabPageXML.Click();
            Delay.Milliseconds(200);
            
            try {
                checkXmlChanges("XmlBoundProperty.txt");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(28)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
